server.port=0
management.endpoints.web.exposure.include=health,info
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
stats.topics.user-actions=stats.user-actions.v1
stats.topics.events-similarity=stats.events-similarity.v1
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.practicum.ewm.stats.kafka.AvroSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.linger.ms=50
spring.kafka.producer.properties.batch.size=65536
spring.kafka.consumer.group-id=aggregator
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=ru.practicum.ewm.stats.kafka.UserActionDeserializer
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=1
stats.aggregation.publish-all-pairs=false
